language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
    - npm install -g yarn
    - yarn global add @vue/cli
    - export PATH=$PATH:$HOME/.yarn/bin
    - vue --version
    - yarn install --network-timeout 1000000
script:
  - yarn lint
  - yarn build --base-href https://tronsmartcontract.space/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  repo: TronSCS/TronSCS.github.io
  target-branch: master
  on:
    branch: master